#!/usr/bin/env python3
from subprocess import Popen, PIPE
from flask import Flask, request, abort
app = Flask(__name__)

@app.route('/time')
@app.route('/getTime')
def get_time():
    process = Popen('date +"%A, %B %d, %Y %H:%M:%S"', shell=True, stdout=PIPE, stderr=PIPE)
    stdout, stderr = process.communicate()
    date = stdout.rstrip().decode()
    return date


if __name__ == '__main__':
    # app.run(debug=True, host='0.0.0.0', port=4123, ssl_context='adhoc')
    app.run(debug=True, host='0.0.0.0', port=4234)
